// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtuwfzzgsueahgmjfvur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dXdmenpnc3VlYWhnbWpmdnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzE5NDcsImV4cCI6MjA2ODUwNzk0N30.W1EJ7fr7jFg_6i1urQ4jSWze8duoc4FsLIHEZuKvkbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});